# Generated by Django 5.2.17 on 2026-09-11 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        max_length=9,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{4}-\\d{2}$",
                                "Use the format YYYY-YY, for example 2026-27.",
                            )
                        ],
                        verbose_name="label",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                ("end_date", models.DateField(verbose_name="end date")),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="current"),
                ),
            ],
            options={
                "verbose_name": "academic year",
                "verbose_name_plural": "academic years",
                "ordering": ["-start_date"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gt", models.F("start_date"))),
                        name="academic_year_ends_after_start",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("is_current",),
                        name="uniq_current_academic_year",
                    ),
                ],
            },
        ),
    ]
