# Generated by Django 5.2.17 on 2026-09-11 06:46

import accounts.models
import accounts.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, unique=True, verbose_name="name"),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="code"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "department",
                "verbose_name_plural": "departments",
                "ordering": ["name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("code", django.db.models.functions.text.Upper("code"))
                        ),
                        name="department_code_uppercase",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "salutation",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="salutation"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="full name"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("FACULTY", "Faculty"), ("PRINCIPAL", "Principal")],
                        default="FACULTY",
                        max_length=20,
                        verbose_name="role",
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("LECTURER", "Lecturer"),
                            ("ASST_PROF", "Assistant Professor"),
                            ("ASSOC_PROF", "Associate Professor"),
                            ("PROFESSOR", "Professor"),
                            ("HOD", "Head of Department"),
                            ("PRINCIPAL", "Principal"),
                            ("OTHER", "Other"),
                        ],
                        max_length=40,
                        verbose_name="designation",
                    ),
                ),
                (
                    "govt_class",
                    models.CharField(
                        choices=[
                            ("CLASS_I", "Class I"),
                            ("CLASS_II", "Class II"),
                            ("CLASS_III", "Class III"),
                            ("CLASS_IV", "Class IV"),
                        ],
                        max_length=20,
                        verbose_name="government class",
                    ),
                ),
                (
                    "employee_code",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="employee code"
                    ),
                ),
                (
                    "joining_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="joining date"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a 10-digit mobile number, optionally starting with +91.",
                                regex="^(\\+91)?\\d{10}$",
                            )
                        ],
                        verbose_name="mobile",
                    ),
                ),
                (
                    "signature_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="signatures/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg"]
                            ),
                            accounts.validators.validate_signature_image,
                        ],
                        verbose_name="signature image",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="admin access"),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="record created"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.department",
                        verbose_name="department",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "ordering": ["full_name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("employee_code", ""), _negated=True),
                        fields=("employee_code",),
                        name="uniq_employee_code_when_set",
                    )
                ],
            },
            managers=[
                ("objects", accounts.models.UserManager()),
            ],
        ),
    ]
