# Generated by Django 5.2.17 on 2026-09-11 07:03

import committees.models
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Committee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="name"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=15,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z0-9]+$",
                                "Use capital letters and digits only, for example TPU.",
                            )
                        ],
                        verbose_name="code",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "allows_multiple_members",
                    models.BooleanField(
                        default=True,
                        help_text="If unticked, only a convener may be assigned.",
                        verbose_name="allows multiple members",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "committee",
                "verbose_name_plural": "committees",
                "ordering": ["name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("code", django.db.models.functions.text.Upper("code"))
                        ),
                        name="committee_code_uppercase",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CommitteeTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(verbose_name="version")),
                (
                    "docx_file",
                    models.FileField(
                        max_length=255,
                        upload_to=committees.models.committee_template_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["docx"]
                            )
                        ],
                        verbose_name="Word file",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="uploaded at"),
                ),
                (
                    "detected_placeholders",
                    models.JSONField(
                        blank=True, default=list, verbose_name="detected placeholders"
                    ),
                ),
                (
                    "committee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="templates",
                        to="committees.committee",
                        verbose_name="committee",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="uploaded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "committee template",
                "verbose_name_plural": "committee templates",
                "ordering": ["committee_id", "-version"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("committee",),
                        name="uniq_active_committee_template",
                    )
                ],
                "unique_together": {("committee", "version")},
            },
        ),
    ]
