# Generated by Django 5.2.17 on 2026-09-11 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("committees", "0001_initial"),
        ("core", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("CONVENER", "Convener"), ("MEMBER", "Member")],
                        max_length=20,
                        verbose_name="role",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUPERSEDED", "Superseded"),
                            ("RELINQUISHED", "Relinquished"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="end date"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.academicyear",
                        verbose_name="academic year",
                    ),
                ),
                (
                    "committee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="committees.committee",
                        verbose_name="committee",
                    ),
                ),
                (
                    "ending_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ended_assignments",
                        to="orders.order",
                        verbose_name="ending order",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="faculty",
                    ),
                ),
                (
                    "issuing_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_assignments",
                        to="orders.order",
                        verbose_name="issuing order",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supersedes",
                        to="assignments.assignment",
                        verbose_name="superseded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "assignment",
                "verbose_name_plural": "assignments",
                "ordering": ["-start_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "committee"],
                        name="assignment_status_cttee_idx",
                    ),
                    models.Index(
                        fields=["faculty", "status"],
                        name="assignment_faculty_status_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "ACTIVE")),
                        fields=("faculty", "committee", "role"),
                        name="uniq_active_assignment",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("role", "CONVENER"), ("status", "ACTIVE")),
                        fields=("committee",),
                        name="uniq_active_convener",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("end_date__isnull", True), ("status", "ACTIVE")),
                            models.Q(("status", "ACTIVE"), _negated=True),
                            _connector="OR",
                        ),
                        name="active_has_no_end_date",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["ACTIVE", "CANCELLED"]),
                            ("end_date__isnull", False),
                            _connector="OR",
                        ),
                        name="ended_assignment_has_end_date",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("end_date__isnull", True),
                            ("end_date__gte", models.F("start_date")),
                            _connector="OR",
                        ),
                        name="end_date_not_before_start_date",
                    ),
                ],
            },
        ),
    ]
