# Generated by Django 5.2.17 on 2026-09-11 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        db_index=True, max_length=60, verbose_name="action"
                    ),
                ),
                (
                    "object_type",
                    models.CharField(max_length=60, verbose_name="object type"),
                ),
                (
                    "object_id",
                    models.CharField(max_length=40, verbose_name="object id"),
                ),
                ("summary", models.CharField(max_length=255, verbose_name="summary")),
                (
                    "detail",
                    models.JSONField(blank=True, default=dict, verbose_name="detail"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="user agent"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actor",
                    ),
                ),
            ],
            options={
                "verbose_name": "audit log entry",
                "verbose_name_plural": "audit log entries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["actor", "created_at"], name="audit_actor_created_idx"
                    )
                ],
            },
        ),
    ]
