# Generated by Django 5.2.17 on 2026-09-11 07:03

import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("committees", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_no",
                    models.CharField(
                        max_length=60, unique=True, verbose_name="order number"
                    ),
                ),
                ("order_date", models.DateField(verbose_name="order date")),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("ASSIGNMENT", "Assignment"),
                            ("RELINQUISHMENT", "Relinquishment"),
                            ("CORRIGENDUM", "Corrigendum"),
                        ],
                        max_length=20,
                        verbose_name="order type",
                    ),
                ),
                (
                    "generated_file",
                    models.FileField(
                        max_length=255,
                        upload_to=orders.models.order_file_path,
                        verbose_name="generated file",
                    ),
                ),
                ("render_context", models.JSONField(verbose_name="render context")),
                ("remarks", models.TextField(blank=True, verbose_name="remarks")),
                (
                    "is_cancelled",
                    models.BooleanField(default=False, verbose_name="cancelled"),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, verbose_name="cancellation reason"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.academicyear",
                        verbose_name="academic year",
                    ),
                ),
                (
                    "cancelled_by_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cancels",
                        to="orders.order",
                        verbose_name="cancelled by order",
                    ),
                ),
                (
                    "committee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="committees.committee",
                        verbose_name="committee",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="issued by",
                    ),
                ),
                (
                    "template_used",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="committees.committeetemplate",
                        verbose_name="template used",
                    ),
                ),
            ],
            options={
                "verbose_name": "order",
                "verbose_name_plural": "orders",
                "ordering": ["-order_date", "-created_at"],
                "indexes": [
                    models.Index(fields=["order_date"], name="order_date_idx"),
                    models.Index(
                        fields=["academic_year", "committee"],
                        name="order_year_committee_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("is_cancelled", False),
                            models.Q(("cancellation_reason", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="cancelled_order_has_reason",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OrderSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_number",
                    models.PositiveIntegerField(default=0, verbose_name="last number"),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.academicyear",
                        verbose_name="academic year",
                    ),
                ),
                (
                    "committee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="committees.committee",
                        verbose_name="committee",
                    ),
                ),
            ],
            options={
                "verbose_name": "order sequence",
                "verbose_name_plural": "order sequences",
                "unique_together": {("academic_year", "committee")},
            },
        ),
    ]
